from python:3.6-slim as builder


    # install python dependencies #
    RUN pip3 install cmake
    RUN apt-get update
    RUN apt-get install -y build-essential cmake pkg-config
    RUN apt-get install -y libx11-dev libatlas-base-dev
    RUN apt-get install -y libgtk-3-dev libboost-python-dev
    RUN apt-get install -y python-dev python3-dev python3 wget
    RUN pip3 install -U numpy
    RUN pip3 install gunicorn
    RUN pip3 install flask
    RUN pip3 install face_recognition
    RUN pip3 install opencv-python
    RUN wget http://dlib.net/files/dlib-19.6.tar.bz2
    RUN tar xvf dlib-19.6.tar.bz2
    RUN cd dlib-19.6/; mkdir build; cd build; cmake ..; cmake --build . --config Release; make install; ldconfig; pwd
    RUN pkg-config --libs --cflags dlib-1
    RUN python dlib-19.6/setup.py install
    RUN rm -rf dlib-19.6/dist
    RUN rm -rf dlib-19.6/tools/python/build

    # install redis #
    RUN apt-get install -y redis
    RUN redis-cli -v



    # install reflex for live reload #
    RUN apt-get -y install zsh
    RUN chsh -s /usr/bin/zsh root
    RUN apt-get -y install git golang # 1.13.15
    RUN go get github.com/cespare/reflex

    # move project files to container #
    COPY ./reconhecimento /

    # opens port 5000 #
    EXPOSE 5000
