version: "3.8"
services:
  reconhecimento:
    build:
      context: ./reconhecimento
      dockerfile: "DockerFile"
    ports:
      - "5000:5000"
    volumes:
      - ./reconhecimento/app:/var/www
      - ./reconhecimento/requirements.txt:/requirements.txt
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app # -w 4 = 4 workers

